### ISSUE TITLE
1337

### ISSUE THREAD

**Issue by shayanb** [ENS-Nifty/ens-nifty-frontend#24]
I might be wrong but probably not. Which one of you guys is the proud owner of [0xD0c838486120cdA746CA514F76C70938bF708b90](https://etherscan.io/address/0xd0c838486120cda746ca514f76c70938bf708b90) address? :) 

@okwme @pedrouid @sudoryan

**Comment by shayanb** [comment]
Ah, I believe it's @okwme . 
`0x2e0398f5d379506d21fcc4f3e38ff58eaff4cf327f5375fd6ceed26f085c4ab2`

**Comment by okwme** [comment]
Can't confirm but why do you ask?

**Comment by shayanb** [comment]
@okwme regarding two specific ens domains we participated in their auctions.

**Comment by okwme** [comment]
aha, you've found me!
I hope you're not too upset, I have no intention of keeping the domain from you.

As you can see we're working on a system for tokenizing ENS domain names. We are currently optimizing to be listed on exchanges like openseas and rarebits. I've been jumping in on a few ENS auctions with the intention of directing the instigator to openseas in order to re-acquire them. We'll be able to list them very soon I hope.

Although marshallmcluhan.eth is an amazing domain I have no intention of keeping it from you (is that the one?). I hope this hasn't inconvenienced you too terribly and you're open to trying out our new system in the process. If you have a time sensitive situation or would prefer not to use our system I'd be happy to arrange another way to transfer your domains back to you.

Maybe we can continue communications through email? If so you can contact me at billy [at] bin.am

**Comment by shayanb** [comment]
Yeah tracking you down was an interesting journey and also a scary one, in the sense that how much we are exposing ourselves without knowing, you know? :)

I'll continue this over email.
