### ISSUE TITLE
Domain name not displayed

### ISSUE THREAD

**Issue by pedrouid** [ENS-Nifty/ens-nifty-frontend#46]
Domain name was submitted through the ENS Nifty frontend but failed to display after tokenizing domain.

**Comment by 409H** [comment]
Related transactions:
https://etherscan.io/tx/0x3ec1b8b4487282361ec9d4e4718465d859c9cb1626cc1e0a5b4d1e24035dbc30
https://etherscan.io/tx/0x0e712602cee76c7e28b9df9ca184c251c441eb2c70cb883ab510b353205aed5d

I tokenised `parkingticket.eth` via the frontend.

![image](https://user-images.githubusercontent.com/2313704/48793657-95d67980-ecef-11e8-9da6-a47398a1361d.png)

![image](https://user-images.githubusercontent.com/2313704/48793672-9e2eb480-ecef-11e8-88e3-22f7ddb58d96.png)

![image](https://user-images.githubusercontent.com/2313704/48793690-ac7cd080-ecef-11e8-97e4-59a3ef7b2bfc.png)

**Comment by sudoryan** [comment]
Thanks for the issue @409H. 

The issue is a missing zero is in front when converting the tokenId to hex.

The hash of parking ticket is '0x0774efcc519e63b7ae40a37e877f84bebe59bece72506f5a1f20eceacbc9c123'

The token id is : '3372799225398613639336624365533174947715212841733530233378571460371668386083'

when converted to hex we get: '774EFCC519E63B7AE40A37E877F84BEBE59BECE72506F5A1F20ECEACBC9C123'

**Comment by sudoryan** [comment]
To solve this, we should add 0 padding to ensure the length of the converted hex is a length 64.
